/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "sumador4.v:9" *)
module sumador4(CLK, ENB, RCI, MODO, A, B, Q, RCO);
  (* src = "sumador4.v:20" *)
  wire [3:0] _000_;
  (* src = "sumador4.v:20" *)
  wire _001_;
  (* src = "sumador4.v:25" *)
  wire [4:0] _002_;
  (* src = "sumador4.v:27" *)
  wire [4:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [1:0] _008_;
  wire [1:0] _009_;
  wire [1:0] _010_;
  wire _011_;
  wire [1:0] _012_;
  wire _013_;
  wire [1:0] _014_;
  wire _015_;
  wire [1:0] _016_;
  wire _017_;
  wire [1:0] _018_;
  wire _019_;
  wire [2:0] _020_;
  wire [2:0] _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  (* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:432" *)
  wire [19:0] _029_;
  (* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:428" *)
  wire [3:0] _030_;
  wire [3:0] _031_;
  wire _032_;
  wire _033_;
  (* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:432" *)
  wire [3:0] _034_;
  (* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:428" *)
  wire _035_;
  wire _036_;
  (* src = "sumador4.v:29" *)
  wire [4:0] _037_;
  (* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:203" *)
  wire [4:0] _038_;
  wire [4:0] _039_;
  (* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "4" *)
  wire [4:0] _040_;
  (* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:445" *)
  wire _041_;
  (* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:445" *)
  wire _042_;
  (* src = "sumador4.v:29|<techmap.v>:258" *)
  wire [4:0] _043_;
  (* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:203" *)
  wire [4:0] _044_;
  (* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4" *)
  wire [4:0] _045_;
  wire [4:0] _046_;
  (* src = "sumador4.v:27|<techmap.v>:260" *)
  wire [4:0] _047_;
  (* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)
  wire _048_;
  (* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)
  wire _049_;
  (* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)
  wire _050_;
  (* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:222" *)
  wire _051_;
  (* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:229" *)
  wire _052_;
  (* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)
  wire _053_;
  (* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:222" *)
  wire _054_;
  (* src = "sumador4.v:29|<techmap.v>:260" *)
  wire [4:0] _055_;
  (* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _056_;
  (* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _057_;
  (* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _058_;
  (* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:222" *)
  wire _059_;
  (* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:229" *)
  wire _060_;
  (* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _061_;
  (* src = "sumador4.v:13" *)
  input [3:0] A;
  (* src = "sumador4.v:14" *)
  input [3:0] B;
  (* src = "sumador4.v:9" *)
  input CLK;
  (* src = "sumador4.v:10" *)
  input ENB;
  (* src = "sumador4.v:12" *)
  input [1:0] MODO;
  (* src = "sumador4.v:15" *)
  output [3:0] Q;
  reg [3:0] Q;
  (* src = "sumador4.v:11" *)
  input RCI;
  (* src = "sumador4.v:16" *)
  output RCO;
  reg RCO;
  assign _004_ = _020_[0] |(* src = "sumador4.v:31|sumador4.v:22" *)  MODO[0];
  assign _022_ = _004_ |(* src = "sumador4.v:31|sumador4.v:22" *)  _020_[2];
  assign _005_ = RCI |(* src = "sumador4.v:28|sumador4.v:22" *)  MODO[0];
  assign _023_ = _005_ |(* src = "sumador4.v:28|sumador4.v:22" *)  _020_[2];
  assign _006_ = _020_[0] |(* src = "sumador4.v:27|sumador4.v:22" *)  _021_[1];
  assign _024_ = _006_ |(* src = "sumador4.v:27|sumador4.v:22" *)  MODO[1];
  assign _007_ = RCI |(* src = "sumador4.v:24|sumador4.v:22" *)  _021_[1];
  assign _025_ = _007_ |(* src = "sumador4.v:24|sumador4.v:22" *)  MODO[1];
  assign _008_[0] = _010_[0] |(* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:441" *)  _034_[1];
  assign _008_[1] = _034_[2] |(* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:441" *)  _034_[3];
  assign _035_ = _008_[0] |(* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:441" *)  _008_[1];
  assign _009_[0] = _010_[0] |(* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:445" *)  _033_;
  assign _009_[1] = _027_ |(* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:445" *)  _028_;
  assign _042_ = _009_[0] |(* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:445" *)  _009_[1];
  assign _010_[1] = _029_[11] |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _029_[15];
  assign _011_ = _010_[0] |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _010_[1];
  assign _030_[3] = _011_ |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _029_[19];
  assign _012_[1] = _029_[10] |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _029_[14];
  assign _013_ = _010_[0] |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _012_[1];
  assign _030_[2] = _013_ |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _029_[18];
  assign _014_[1] = _029_[9] |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _029_[13];
  assign _015_ = _010_[0] |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _014_[1];
  assign _030_[1] = _015_ |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _029_[17];
  assign _016_[1] = _029_[8] |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _029_[12];
  assign _017_ = _010_[0] |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _016_[1];
  assign _030_[0] = _017_ |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:441" *)  _029_[16];
  assign _018_[0] = _032_ |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:445" *)  _010_[0];
  assign _018_[1] = _033_ |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:445" *)  _027_;
  assign _019_ = _018_[0] |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:445" *)  _018_[1];
  assign _041_ = _019_ |(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:445" *)  _028_;
  assign _026_ = _007_ |(* src = "sumador4.v:32|sumador4.v:22" *)  _020_[2];
  assign _010_[0] = ~(* src = "sumador4.v:31|sumador4.v:22" *) _022_;
  assign _033_ = ~(* src = "sumador4.v:28|sumador4.v:22" *) _023_;
  assign _027_ = ~(* src = "sumador4.v:27|sumador4.v:22" *) _024_;
  assign _028_ = ~(* src = "sumador4.v:24|sumador4.v:22" *) _025_;
  assign _032_ = ~(* src = "sumador4.v:32|sumador4.v:22" *) _026_;
  assign _000_[0] = ENB ? (* src = "sumador4.v:21" *) _031_[0] : Q[0];
  assign _000_[1] = ENB ? (* src = "sumador4.v:21" *) _031_[1] : Q[1];
  assign _000_[2] = ENB ? (* src = "sumador4.v:21" *) _031_[2] : Q[2];
  assign _000_[3] = ENB ? (* src = "sumador4.v:21" *) _031_[3] : Q[3];
  assign _036_ = _042_ ? (* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:445" *) _035_ : RCO;
  assign _031_[0] = _041_ ? (* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:445" *) _030_[0] : Q[0];
  assign _031_[1] = _041_ ? (* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:445" *) _030_[1] : Q[1];
  assign _031_[2] = _041_ ? (* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:445" *) _030_[2] : Q[2];
  assign _031_[3] = _041_ ? (* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:445" *) _030_[3] : Q[3];
  assign _001_ = ENB ? (* src = "sumador4.v:21" *) _036_ : RCO;
  assign _043_[1] = ~(* src = "sumador4.v:27|<techmap.v>:258" *) B[1];
  assign _043_[2] = ~(* src = "sumador4.v:27|<techmap.v>:258" *) B[2];
  assign _043_[0] = ~(* src = "sumador4.v:29|<techmap.v>:258" *) B[0];
  assign _043_[3] = ~(* src = "sumador4.v:29|<techmap.v>:258" *) B[3];
  (* src = "sumador4.v:20" *)
  always @(posedge CLK)
      Q[0] <= _000_[0];
  (* src = "sumador4.v:20" *)
  always @(posedge CLK)
      Q[1] <= _000_[1];
  (* src = "sumador4.v:20" *)
  always @(posedge CLK)
      Q[2] <= _000_[2];
  (* src = "sumador4.v:20" *)
  always @(posedge CLK)
      Q[3] <= _000_[3];
  (* src = "sumador4.v:20" *)
  always @(posedge CLK)
      RCO <= _001_;
  assign _020_[2] = MODO[1] ^(* src = "sumador4.v:28|sumador4.v:22" *)  1'h1;
  assign _020_[0] = RCI ^(* src = "sumador4.v:27|sumador4.v:22" *)  1'h1;
  assign _021_[1] = MODO[0] ^(* src = "sumador4.v:24|sumador4.v:22" *)  1'h1;
  assign _034_[3] = _002_[4] &(* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:434" *)  _028_;
  assign _034_[2] = _003_[4] &(* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:434" *)  _027_;
  assign _034_[1] = _037_[4] &(* src = "sumador4.v:31|sumador4.v:22|<techmap.v>:434" *)  _033_;
  assign _029_[16] = _002_[0] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _028_;
  assign _029_[17] = _002_[1] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _028_;
  assign _029_[18] = _002_[2] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _028_;
  assign _029_[19] = _002_[3] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _028_;
  assign _029_[12] = _003_[0] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _027_;
  assign _029_[13] = _003_[1] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _027_;
  assign _029_[14] = _003_[2] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _027_;
  assign _029_[15] = _003_[3] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _027_;
  assign _029_[8] = _037_[0] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _033_;
  assign _029_[9] = _037_[1] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _033_;
  assign _029_[10] = _037_[2] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _033_;
  assign _029_[11] = _037_[3] &(* src = "sumador4.v:32|sumador4.v:22|<techmap.v>:434" *)  _033_;
  assign _038_[0] = A[0] &(* src = "sumador4.v:27|<techmap.v>:260" *)  B[0];
  assign _047_[1] = A[1] &(* src = "sumador4.v:27|<techmap.v>:260" *)  B[1];
  assign _047_[2] = A[2] &(* src = "sumador4.v:27|<techmap.v>:260" *)  B[2];
  assign _047_[3] = A[3] &(* src = "sumador4.v:27|<techmap.v>:260" *)  B[3];
  assign _002_[1] = _039_[1] ^(* src = "sumador4.v:27|<techmap.v>:263" *)  _038_[0];
  assign _002_[2] = _039_[2] ^(* src = "sumador4.v:27|<techmap.v>:263" *)  _038_[1];
  assign _002_[3] = _039_[3] ^(* src = "sumador4.v:27|<techmap.v>:263" *)  _038_[2];
  assign _002_[0] = A[0] ^(* src = "sumador4.v:27|<techmap.v>:262" *)  B[0];
  assign _039_[1] = A[1] ^(* src = "sumador4.v:27|<techmap.v>:262" *)  B[1];
  assign _039_[2] = A[2] ^(* src = "sumador4.v:27|<techmap.v>:262" *)  B[2];
  assign _039_[3] = A[3] ^(* src = "sumador4.v:27|<techmap.v>:262" *)  B[3];
  assign _003_[1] = _002_[1] ^(* src = "sumador4.v:27|<techmap.v>:263" *)  _002_[0];
  assign _003_[2] = _002_[2] ^(* src = "sumador4.v:27|<techmap.v>:263" *)  _040_[1];
  assign _003_[3] = _002_[3] ^(* src = "sumador4.v:27|<techmap.v>:263" *)  _040_[2];
  assign _003_[4] = _002_[4] ^(* src = "sumador4.v:27|<techmap.v>:263" *)  _040_[3];
  assign _003_[0] = 1'h1 ^(* src = "sumador4.v:27|<techmap.v>:262" *)  _002_[0];
  assign _055_[0] = A[0] &(* src = "sumador4.v:29|<techmap.v>:260" *)  _043_[0];
  assign _055_[1] = A[1] &(* src = "sumador4.v:29|<techmap.v>:260" *)  _043_[1];
  assign _055_[2] = A[2] &(* src = "sumador4.v:29|<techmap.v>:260" *)  _043_[2];
  assign _055_[3] = A[3] &(* src = "sumador4.v:29|<techmap.v>:260" *)  _043_[3];
  assign _037_[0] = _045_[0] ^(* src = "sumador4.v:29|<techmap.v>:263" *)  1'h1;
  assign _037_[1] = _046_[1] ^(* src = "sumador4.v:29|<techmap.v>:263" *)  _044_[0];
  assign _037_[2] = _046_[2] ^(* src = "sumador4.v:29|<techmap.v>:263" *)  _044_[1];
  assign _037_[3] = _046_[3] ^(* src = "sumador4.v:29|<techmap.v>:263" *)  _044_[2];
  assign _037_[4] = 1'h1 ^(* src = "sumador4.v:29|<techmap.v>:263" *)  _044_[4];
  assign _045_[0] = A[0] ^(* src = "sumador4.v:29|<techmap.v>:262" *)  _043_[0];
  assign _046_[1] = A[1] ^(* src = "sumador4.v:29|<techmap.v>:262" *)  _043_[1];
  assign _046_[2] = A[2] ^(* src = "sumador4.v:29|<techmap.v>:262" *)  _043_[2];
  assign _046_[3] = A[3] ^(* src = "sumador4.v:29|<techmap.v>:262" *)  _043_[3];
  assign _048_ = _039_[1] &(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)  _038_[0];
  assign _049_ = _039_[3] &(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)  _047_[2];
  assign _050_ = _051_ &(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)  _038_[1];
  assign _051_ = _039_[3] &(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:222" *)  _039_[2];
  assign _052_ = _039_[2] &(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:229" *)  _038_[1];
  assign _038_[1] = _047_[1] |(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)  _048_;
  assign _053_ = _047_[3] |(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)  _049_;
  assign _002_[4] = _053_ |(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)  _050_;
  assign _038_[2] = _047_[2] |(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:229" *)  _052_;
  assign _040_[1] = _002_[1] &(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)  _002_[0];
  assign _040_[3] = _054_ &(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:221" *)  _040_[1];
  assign _054_ = _002_[3] &(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:222" *)  _002_[2];
  assign _040_[2] = _002_[2] &(* src = "sumador4.v:27|<techmap.v>:260|<techmap.v>:229" *)  _040_[1];
  assign _056_ = _046_[1] &(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)  _044_[0];
  assign _057_ = _046_[3] &(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)  _055_[2];
  assign _058_ = _059_ &(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)  _044_[1];
  assign _059_ = _046_[3] &(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:222" *)  _046_[2];
  assign _060_ = _046_[2] &(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:229" *)  _044_[1];
  assign _044_[0] = _055_[0] |(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:212" *)  _045_[0];
  assign _044_[1] = _055_[1] |(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)  _056_;
  assign _061_ = _055_[3] |(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)  _057_;
  assign _044_[4] = _061_ |(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:221" *)  _058_;
  assign _044_[2] = _055_[2] |(* src = "sumador4.v:29|<techmap.v>:260|<techmap.v>:229" *)  _060_;
  assign _012_[0] = _010_[0];
  assign _014_[0] = _010_[0];
  assign _016_[0] = _010_[0];
  assign _020_[1] = MODO[0];
  assign { _021_[2], _021_[0] } = { MODO[1], _020_[0] };
  assign _029_[7:0] = { _010_[0], _010_[0], _010_[0], _010_[0], 4'h0 };
  assign _034_[0] = _010_[0];
  assign _038_[4:3] = { 1'h0, _002_[4] };
  assign { _039_[4], _039_[0] } = { 1'h0, _002_[0] };
  assign _040_[0] = _002_[0];
  assign _043_[4] = 1'h1;
  assign _044_[3] = _044_[4];
  assign { _046_[4], _046_[0] } = { 1'h1, _045_[0] };
  assign { _047_[4], _047_[0] } = { 1'h0, _038_[0] };
  assign _055_[4] = 1'h0;
endmodule
